# Generated by Django 3.2.5 on 2022-09-26 08:09

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empfname', models.CharField(max_length=100)),
                ('emplname', models.CharField(max_length=100)),
                ('empdept', models.CharField(max_length=100)),
                ('emplocation', models.CharField(max_length=100, null=True)),
                ('empphone', models.CharField(max_length=15, unique=True)),
                ('empemail', models.CharField(max_length=100, unique=True)),
                ('emppassword', models.CharField(max_length=125)),
                ('empassignstatus', models.BooleanField()),
                ('empintassignstatus', models.BooleanField()),
                ('last_login', models.DateTimeField(null=True)),
                ('last_logout', models.DateTimeField(null=True)),
                ('languages', django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=140, size=6)),
                ('firstlan', models.CharField(max_length=255)),
                ('seclan', models.CharField(max_length=255)),
                ('thirdlan', models.CharField(max_length=255)),
                ('source', django_mysql.models.ListCharField(models.CharField(max_length=20), default='Organic', max_length=140, size=6)),
                ('columns_prospect', django_mysql.models.ListCharField(models.CharField(max_length=40), max_length=1250, size=25)),
                ('columns_investor', django_mysql.models.ListCharField(models.CharField(max_length=40), max_length=1250, size=25)),
                ('empnickname', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(null=True, upload_to='ProfilePics/')),
                ('empcreateddt', models.DateTimeField(auto_now_add=True)),
                ('empupdateddt', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_by', models.IntegerField(null=True)),
                ('reporting_to', models.CharField(max_length=100, null=True)),
                ('cap', models.IntegerField(null=True)),
                ('cap_reached', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
