# Generated by Django 3.2.5 on 2022-09-26 08:42

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='columns_investor',
            field=django_mysql.models.ListCharField(models.CharField(max_length=40), max_length=1250, null=True, size=25),
        ),
        migrations.AlterField(
            model_name='employee',
            name='columns_prospect',
            field=django_mysql.models.ListCharField(models.CharField(max_length=40), max_length=1250, null=True, size=25),
        ),
        migrations.AlterField(
            model_name='employee',
            name='empassignstatus',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='empintassignstatus',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='empnickname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='firstlan',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='languages',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=140, null=True, size=6),
        ),
        migrations.AlterField(
            model_name='employee',
            name='seclan',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='thirdlan',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
